-include ../global.mk

# Aliases for executables
# CP ?= cp
# GH ?= gh
# GIT ?= git
# RM ?= rm
# SED ?= sed
STACK ?= stack

# Exercism variables
SUBMISSIONS = $(EXERCISE)
TRACK = haskell

# boot-tests::
# 	$(GIT) add $(EXERCISE)/
# 	$(GIT) commit -m "Enable all tests"

test::
	$(STACK) test

# coverage::
# clean::
