(defpackage :scrabble-score
  (:use :cl)
  (:export :score-word))

(in-package :scrabble-score)

(defun letter-score-p (letter)
  "Returns the score for a single letter."
  (case letter
    (#\a 1)
    (#\b 3)
    (#\c 3)
    (#\d 2)
    (#\e 1)
    (#\f 4)
    (#\g 2)
    (#\h 4)
    (#\i 1)
    (#\j 8)
    (#\k 5)
    (#\l 1)
    (#\m 3)
    (#\n 1)
    (#\o 1)
    (#\p 3)
    (#\q 10)
    (#\r 1)
    (#\s 1)
    (#\t 1)
    (#\u 1)
    (#\v 4)
    (#\w 4)
    (#\x 8)
    (#\y 4)
    (#\z 10)
    (t 0)))

(defun score-word (word)
  "Computes the score for an entire word."
  (reduce #'+ (mapcar #'letter-score-p (coerce (string-downcase word) 'list))))
