-include ../global.mk

# Aliases for executables
# CP ?= cp
# GH ?= gh
# GIT ?= git
PROVE ?= prove
# RM ?= rm
# SED ?= sed

# Exercism variables
SUBMISSIONS = lib/$(EXERCISE_PASCAL_CASE).pm
TRACK = perl5

# boot-tests::
# 	$(GIT) add $(EXERCISE)/
# 	$(GIT) commit -m "Enable all tests"

test::
	$(PROVE)

# coverage::
# clean::
