-include ../global.mk

# Aliases for executables
BATS ?= bats
CODE ?= code
EXERCISM ?= exercism
FIND ?= find
GH ?= gh
GIT ?= git
RM ?= rm
SED ?= sed
XDG_OPEN ?= xdg-open

# Exercism variables
SUBMISSIONS = $(EXERCISE).jq
TRACK = jq

# boot-tests::
# 	$(GIT) add $(EXERCISE)/
# 	$(GIT) commit -m "Enable all tests"
test:: test-bats
# coverage::
# clean::
