-include ../global.mk

# Aliases for executables
# CP ?= cp
FIND ?= find
# GH ?= gh
# GIT ?= git
# RM ?= rm
# SED ?= sed

# Exercism variables
SUBMISSIONS = $(shell $(FIND) . -type f -name '*.u' -and -not -name '*.test.u')
TRACK = unison

# boot-tests::
# 	$(GIT) add $(EXERCISE)/
# 	$(GIT) commit -m "Enable all tests"
# test::
# coverage::
# clean::
