-include ../global.mk

# Aliases for executables
# CP ?= cp
CRYSTAL ?= crystal
# GH ?= gh
# GIT ?= git
# RM ?= rm
# SED ?= sed

# Exercism variables
SUBMISSIONS = src/$(EXERCISE_SNAKE_CASE).cr
TRACK = crystal

# boot-tests::

test::
	$(CRYSTAL) spec

# coverage::
# clean::
